[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [{ name = "fixedbitset", version = "0.4.2" }]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "MIT",
    "Unicode-DFS-2016",
]
exceptions = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
