[package]
name = "bevy_replicon_spawn"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_replicon = { workspace = true }
bevy_replicon_spawn_macros = { path = "../bevy_replicon_spawn" }
